# Generated by Django 4.0.3 on 2022-03-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_item_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='title',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
